name: clang

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]

    env:
      CC: clang
      CXX: clang++
      BUILD_EXAMPLES: ON

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCMAKE_C_COMPILER=${{env.CC}} \
          -DCMAKE_CXX_COMPILER=${{env.CXX}} \
          -Ddeepptr_BUILD_EXAMPLES=${{env.BUILD_EXAMPLES}}

    - name: Build
      run: cmake --build build -j $(nproc)

    - name: Test
      run: ctest -C ${{matrix.build_type}} --test-dir build/tests/
